Tries to add Iter to List, but impl is missing lifetime specs.
   Compiling lists v0.1.0 (file:///home/ardent/rust-stuff/lists)
error[E0106]: missing lifetime specifier
 --> src/second.rs:3:18
  |
3 |     next: Option<&Node<T>>,
  |                  ^ expected lifetime parameter

error[E0106]: missing lifetime specifier
  --> src/second.rs:81:17
   |
81 |     type Item = &T;
   |                 ^ expected lifetime parameter

error: aborting due to 2 previous errors