Breaks pop() by using value after move.
error[E0382]: use of moved value: `node`
  --> src/first.rs:36:22
   |
35 |                 self.head = node.next;
   |                             --------- value moved here
36 |                 Some(node.elem)
   |                      ^^^^^^^^^ value used here after move
   |
   = note: move occurs because `node.next` has type `first::Link`, which does not implement the `Copy` trait